(function () {
    "use strict";

    // ==================================================
    // STATE
    // ==================================================

    let lastPrompt = "";
    let isAutoOptimizing = false;

    /*
     * True only while the extension itself is inserting
     * the optimized prompt.
     */
    let extensionIsInserting = false;

    const AUTO_OPTIMIZE_LIMIT = 500;


    // ==================================================
    // FIND CHATGPT PROMPT BOX
    // ==================================================

    function findPromptBox() {

        const elements =
            document.querySelectorAll(
                'textarea, div[contenteditable="true"]'
            );

        const visibleElements =
            Array.from(elements).filter(element => {

                const style =
                    window.getComputedStyle(element);

                const rect =
                    element.getBoundingClientRect();

                return (
                    style.display !== "none" &&
                    style.visibility !== "hidden" &&
                    rect.width > 0 &&
                    rect.height > 0
                );
            });

        if (!visibleElements.length) {
            return null;
        }

        /*
         * Prefer currently focused textbox.
         */
        const active =
            document.activeElement;

        if (
            active &&
            (
                active.tagName?.toLowerCase() === "textarea" ||
                active.isContentEditable
            ) &&
            visibleElements.includes(active)
        ) {
            return active;
        }

        /*
         * Prefer contenteditable.
         */
        const contentEditable =
            visibleElements.find(
                element =>
                    element.getAttribute(
                        "contenteditable"
                    ) === "true"
            );

        if (contentEditable) {
            return contentEditable;
        }

        return visibleElements[
            visibleElements.length - 1
        ];
    }


    // ==================================================
    // GET TEXT FROM PROMPT BOX
    // ==================================================

    function getPromptText(element) {

        if (!element) {
            return "";
        }

        if (
            element.tagName &&
            element.tagName.toLowerCase() === "textarea"
        ) {
            return element.value.trim();
        }

        return (
            element.innerText ||
            element.textContent ||
            ""
        ).trim();
    }


    // ==================================================
    // HANDLE USER INPUT
    // ==================================================

    function handleUserInput(element) {

        const prompt =
            getPromptText(element);

        if (!prompt) {
            return;
        }

        /*
         * Ignore ONLY input generated by our own
         * optimized-prompt insertion.
         */
        if (extensionIsInserting) {

            console.log(
                "SGP Token Optimizer: Ignoring extension-generated input."
            );

            return;
        }

        /*
         * Ignore duplicate events.
         */
        if (prompt === lastPrompt) {
            return;
        }

        lastPrompt = prompt;

        console.log(
            "SGP Token Optimizer: Latest prompt:",
            prompt
        );


        // ==================================================
        // SAVE PROMPT FOR POPUP
        // ==================================================

        chrome.storage.local.set({
            detectedPrompt: prompt,
            detectedAt: Date.now(),
            detectedSource: "chatgpt"
        });


        // ==================================================
        // SEND PROMPT TO POPUP
        // ==================================================

        chrome.runtime.sendMessage({
            type: "PROMPT_DETECTED",
            prompt: prompt
        }).catch(() => {});


        // ==================================================
        // CHECK PROMPT LENGTH
        // ==================================================

        if (
            prompt.length <= AUTO_OPTIMIZE_LIMIT
        ) {

            console.log(
                "SGP Token Optimizer: Prompt is under 500 characters."
            );

            return;
        }


        // ==================================================
        // CHECK IF OPTIMIZATION IS ALREADY RUNNING
        // ==================================================

        if (isAutoOptimizing) {

            console.log(
                "SGP Token Optimizer: Optimization already running."
            );

            return;
        }


        // ==================================================
        // START AUTOMATIC OPTIMIZATION
        // ==================================================

        isAutoOptimizing = true;

        console.log(
            "SGP Token Optimizer: Prompt is over 500 characters."
        );

        console.log(
            "SGP Token Optimizer: Starting automatic optimization..."
        );


        chrome.runtime.sendMessage({
            type: "AUTO_OPTIMIZE_PROMPT",
            prompt: prompt
        }).catch(error => {

            console.error(
                "SGP Token Optimizer: Failed to send optimization request:",
                error
            );

            isAutoOptimizing = false;
        });
    }


    // ==================================================
    // PROCESS PROMPT BOX
    // ==================================================

    function processPromptBox(element) {

        if (!element) {
            return;
        }

        if (extensionIsInserting) {

            console.log(
                "SGP Token Optimizer: Ignoring extension-generated change."
            );

            return;
        }

        handleUserInput(element);
    }


    // ==================================================
    // INPUT EVENT
    // ==================================================

    document.addEventListener(
        "input",
        function (event) {

            console.log(
                "SGP Token Optimizer: INPUT EVENT DETECTED",
                event.target
            );

            const target =
                event.target;

            if (!target) {
                return;
            }

            const isTextarea =
                target.tagName &&
                target.tagName.toLowerCase() ===
                    "textarea";

            const isContentEditable =
                target.isContentEditable ||
                target.getAttribute?.(
                    "contenteditable"
                ) === "true";

            if (
                isTextarea ||
                isContentEditable
            ) {

                console.log(
                    "SGP Token Optimizer: Valid prompt box detected."
                );

                processPromptBox(target);
            }

        },
        true
    );


    // ==================================================
    // PASTE EVENT
    // ==================================================

    document.addEventListener(
        "paste",
        function (event) {

            console.log(
                "SGP Token Optimizer: PASTE EVENT DETECTED"
            );

            const target =
                event.target;

            if (!target) {
                return;
            }

            const isTextarea =
                target.tagName &&
                target.tagName.toLowerCase() ===
                    "textarea";

            const isContentEditable =
                target.isContentEditable ||
                target.getAttribute?.(
                    "contenteditable"
                ) === "true";

            if (
                !isTextarea &&
                !isContentEditable
            ) {
                return;
            }

            /*
             * ChatGPT may update the textbox after
             * the paste event has fired.
             */
            setTimeout(() => {

                if (extensionIsInserting) {

                    console.log(
                        "SGP Token Optimizer: Ignoring extension-generated paste."
                    );

                    return;
                }

                console.log(
                    "SGP Token Optimizer: Processing pasted prompt."
                );

                /*
                 * Use the current prompt box if ChatGPT
                 * replaced the original DOM element.
                 */
                const currentPromptBox =
                    findPromptBox();

                if (currentPromptBox) {

                    processPromptBox(
                        currentPromptBox
                    );

                } else {

                    processPromptBox(
                        target
                    );
                }

            }, 100);

        },
        true
    );


    // ==================================================
    // INSERT OPTIMIZED PROMPT
    // ==================================================

    function insertOptimizedPrompt(prompt) {

        if (!prompt) {

            console.error(
                "SGP Token Optimizer: Empty optimized prompt."
            );

            isAutoOptimizing = false;

            return;
        }


        const promptBox =
            findPromptBox();


        if (!promptBox) {

            console.error(
                "SGP Token Optimizer: ChatGPT textbox not found."
            );

            isAutoOptimizing = false;

            return;
        }


        /*
         * Tell input/paste handlers that the following
         * changes are generated by the extension.
         */
        extensionIsInserting = true;


        /*
         * Synchronize our state.
         */
        lastPrompt = prompt;


        // ==================================================
        // TEXTAREA
        // ==================================================

        if (
            promptBox.tagName.toLowerCase() ===
            "textarea"
        ) {

            const setter =
                Object.getOwnPropertyDescriptor(
                    HTMLTextAreaElement.prototype,
                    "value"
                ).set;

            setter.call(
                promptBox,
                prompt
            );


            promptBox.dispatchEvent(
                new Event(
                    "input",
                    {
                        bubbles: true
                    }
                )
            );


            promptBox.dispatchEvent(
                new Event(
                    "change",
                    {
                        bubbles: true
                    }
                )
            );


            console.log(
                "SGP Token Optimizer: Optimized prompt inserted into textarea."
            );
        }


        // ==================================================
        // CONTENTEDITABLE
        // ==================================================

        else {

            promptBox.focus();

            promptBox.innerHTML = "";


            const textNode =
                document.createTextNode(
                    prompt
                );


            promptBox.appendChild(
                textNode
            );


            promptBox.dispatchEvent(
                new InputEvent(
                    "input",
                    {
                        bubbles: true,
                        inputType: "insertText",
                        data: prompt
                    }
                )
            );


            console.log(
                "SGP Token Optimizer: Optimized prompt inserted into contenteditable."
            );
        }


        promptBox.focus();


        // ==================================================
        // RELEASE INSERTION LOCK
        // ==================================================

        setTimeout(() => {

            extensionIsInserting = false;

            lastPrompt = prompt;

            isAutoOptimizing = false;

            console.log(
                "SGP Token Optimizer: Extension insertion finished."
            );

            console.log(
                "SGP Token Optimizer: Ready for new user input."
            );

        }, 300);
    }


    // ==================================================
    // AUTOMATIC OPTIMIZATION FINISHED
    // ==================================================

    function autoOptimizationFinished(
        optimizedPrompt
    ) {

        console.log(
            "SGP Token Optimizer: Received optimized prompt."
        );


        if (!optimizedPrompt) {

            console.error(
                "SGP Token Optimizer: No optimized prompt received."
            );

            isAutoOptimizing = false;

            return;
        }


        insertOptimizedPrompt(
            optimizedPrompt
        );
    }


    // ==================================================
    // MESSAGES FROM BACKGROUND / POPUP
    // ==================================================

    chrome.runtime.onMessage.addListener(
        function (message) {

            if (!message) {
                return;
            }


            // ==================================================
            // AUTOMATIC OPTIMIZATION RESULT
            // ==================================================

            if (
                message.type ===
                "AUTO_OPTIMIZED_PROMPT"
            ) {

                autoOptimizationFinished(
                    message.prompt
                );
            }


            // ==================================================
            // AUTOMATIC OPTIMIZATION FAILED
            // ==================================================

            if (
                message.type ===
                "AUTO_OPTIMIZATION_FAILED"
            ) {

                isAutoOptimizing = false;

                extensionIsInserting = false;

                console.log(
                    "SGP Token Optimizer: Automatic optimization failed."
                );
            }


            // ==================================================
            // MANUAL OPTIMIZATION FROM POPUP
            // ==================================================

            if (
                message.type ===
                "INSERT_OPTIMIZED_PROMPT"
            ) {

                if (!message.prompt) {
                    return;
                }


                /*
                 * Manual insertion should also be protected
                 * from triggering automatic optimization.
                 */
                lastPrompt =
                    message.prompt;


                insertOptimizedPrompt(
                    message.prompt
                );


                console.log(
                    "SGP Token Optimizer: Manual optimized prompt inserted."
                );
            }

        }
    );


    // ==================================================
    // START
    // ==================================================

    console.log(
        "SGP Token Optimizer: Content script loaded."
    );

})();